name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Generate token
        id: generatetok
        run : |
              $source = "E:\Project\Travel\bin"
              $destination = "C:\Logs"
              Get-ChildItem $source -Recurse | Copy-Item -Destination $destination
              
              Remove-Item $source\* -Force -Recurse
        shell: powershell
        
      - name: Generate token
        id: generate-tko
        run :  |
              echo "The message is ${{ steps.generatetok.outputs.production }}"
