name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install Newman
        run : npm install -g newman && npm install -g newman-reporter-htmlextra  
        shell: cmd
        
      - name: Generate token
        id: generatetok
        run : |
               Invoke-Expression ".\reg.bat"
        shell: powershell
        working-directory: D:\publishdata
        

